#!/bin/bash

# Ansi color code variables
red="\e[0;91m"
blue="\e[0;94m"
green="\e[0;92m"
white="\e[0;97m"
cyan="\e[0;46m"
yellow="\e[0;33m"
bold="\e[1m"
uline="\e[4m"
reset="\e[0m"

#######################################
#Record date of creation for log file.#
#######################################

d=$(date +"%Y-%m-%d_%T")
echo "$d"

#################################
#Forward all output to log file.#
#################################

log_file="SplunkInstall_log_$d.txt"

touch "./SplunkInstall_log_$d.txt"

exec &> >(tee -a "/var/log/$log_file")

###################################
#Check if running process as root.#
###################################

if [[ $EUID -ne 0 ]]; then

	echo "**********************************"
	echo -e "${red}${bold}This Installer must be run as root!${reset}"
	echo "**********************************"

	echo ""

exit 1

fi

set -e

if [[ -d "/opt/splunkforwarder" ]]

then
        echo -e "${blue}${bold}==========================================${reset}"
        echo -e "${red}${bold}Detected older version of Splunk Installed${reset}"
        echo -e "${blue}${bold}==========================================${reset}"
	echo ""
	echo ""
        echo -e "${blue}${bold}===============================================================${reset}"
        echo -e "${white}${bold}Please wait while attempting to remove the older Splunk install${reset}"
        echo -e "${blue}${bold}===============================================================${reset}"
	echo ""
	echo ""
        echo -e "${cyan}${bold}************************************${reset}"
        echo -e "${yellow}Splunk${reset}${green}${bold}>${reset}${white}${bold}Because ninjas are too busy${reset}"
        echo -e "${cyan}${bold}************************************${reset}"
	echo ""
	echo ""

./resetsplunk.sh

sleep 5

else
        echo -e "${blue}${bold}=====================================${reset}"
        echo -e "${white}${bold}Installation is good to move forward${reset}"
        echo -e "${blue}${bold}=====================================${reset}"
	echo ""
	echo ""
	echo -e "${cyan}${bold}************************************${reset}"
        echo -e "${yellow}Splunk${reset}${green}${bold} > ${reset}${white}${bold}Because ninjas are too busy${reset}"
        echo -e "${cyan}${bold}************************************${reset}"


fi

################################################
# Function to add user to the appropriate group#
################################################

add_user_to_group() {
    if [ "$1" == "yum" ] || [ "$1" == "dnf" ]; then
        # Add Splunk user to the wheel group (RHEL/CentOS distrobutions)
        usermod -aG wheel splunk

elif [ "$1" == "apt" ]; then
        # Add Splunk user to the sudo group (Debian/Ubuntu base distrobutions)
        usermod -aG sudo splunk
    fi
}

#####################################################################
#Install the correct package after determining the Operating System.#
#####################################################################

if command -v dnf &> /dev/null; then
    package_manager="dnf"
elif command -v yum &> /dev/null; then
    package_manager="yum"
elif command -v apt-get &> /dev/null; then
    package_manager="apt"
else
    echo -e "${red}${bold}Unsupported package manager or distribution.${reset}"
    exit 1
fi

    echo ""
    echo -e "${blue}${bold}=========================================================${reset}"
    echo -e "${white}${bold}Detecting Operating System to install the correct package${reset}"
    echo -e "${blue}${bold}=========================================================${reset}"
    echo ""
    echo ""
    echo -e "${cyan}${bold}**********************************************${reset}"
    echo -e "${yellow}Splunk${reset}${green}${bold} > ${reset}${white}${bold}More flexible than an Olympic gymnast${reset}"
    echo -e "${cyan}${bold}**********************************************${reset}"
    echo ""
    echo ""

#####################################################################

RPM_PACKAGE_NAME="splunkInstaller.rpm"
DEB_PACKAGE_NAME="splunkInstaller.deb"

#######################################
# Determine distribution's pretty name#
#######################################

pretty_name=$(cat /etc/*release | grep -i ^PRETTY_NAME)

####################################################################

case $package_manager in
    dnf|yum)
        echo -e "${blue}${bold}Installing packages $RPM_PACKAGE_NAME on $pretty_name${reset}"
        rpm -i $RPM_PACKAGE_NAME
	sleep 10
	add_user_to_group "wheel"
        ;;
    apt)
        echo -e "${blue}${bold}Installing packages $DEB_PACKAGE_NAME on $pretty_name${reset}"
        dpkg --install $DEB_PACKAGE_NAME
	sleep 10
	add_user_to_group "sudo"
        ;;
esac

##############################################
#Copy Config files to local system directory.#
##############################################

cp user-seed.conf /opt/splunkforwarder/etc/system/local/
cp deploymentclient.conf /opt/splunkforwarder/etc/system/local/

###################################################
#Grant the new Splunk user ownership of directory.#
###################################################

chown -R splunk:splunk /opt/splunkforwarder/

###############################################################################
#Add the newly created Splunk user to the wheel group to enable read for logs.#
###############################################################################

	echo ""
	echo ""
	echo -e "${blue}${bold}===============================${reset}"
	echo -e "${white}${bold}Granting new Splunk user access${reset}"
	echo -e "${blue}${bold}===============================${reset}"
	echo ""
	echo ""
	echo -e "${cyan}${bold}******************************************${reset}"
	echo -e "${yellow}Splunk${reset}${green}${bold} > ${reset}${white}${bold}The mars rover of the IT landfill${reset}"
	echo -e "${cyan}${bold}******************************************${reset}"

############################
#Activate and start splunk.#
############################

/opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt

##############################
#Check if setacl is installed#
##############################

if ! command -v setfacl &> /dev/null; then
    echo "The 'setfacl' command is not available. Please install it to proceed."
    exit 1
fi

####################################################################
#Creating ACLs for Log Rotation Permission to continue to read logs#
####################################################################

setfacl -R -m u:splunk:r-x /var/log

touch "/etc/logrotate.d/Splunk_ACLs"

cat <<EOF >> "/etc/logrotate.d/Splunk_ACLs"

{
    postrotate

        /usr/bin/setfacl -R -m u:splunk:r-x /var/log

    endscript
}

EOF

#chown -R splunk:splunk /opt/splunkforwarder/

sleep 5

	echo -e "${blue}${bold}==================================${reset}"
	echo -e "${white}${bold}Accepting Splunk License Agreement${reset}"
	echo -e "${blue}${bold}==================================${reset}"
	echo ""
	echo ""

#sudo -u splunk /opt/splunkforwarder/bin/splunk stop

/opt/splunkforwarder/bin/splunk stop

#################################
#Enable splunk to start at boot.#
#################################

	echo -e "${blue}${bold}===================================${reset}"
	echo -e "${white}${bold}Configuring Splunk to start at boot${reset}"
	echo -e "${blue}${bold}===================================${reset}"
	echo ""
	echo ""

/opt/splunkforwarder/bin/splunk enable boot-start -systemd-managed 1

sleep 5
##################################################################################################################################
# Please replace "yourdomain" with your domain if you have a mix enviroment that has some linux machines tied to Active Directory#
##################################################################################################################################
sed -i "s/splunk@yourdomain:domain\ users@yourdomain/\'splunk@yourdomain:domain\ users@yourdomain\'/g" /etc/systemd/system/SplunkForwarder.service

sleep 5

systemctl daemon-reload

sleep 10

chown -R splunk:splunk /opt/splunkforwarder/

	echo -e "${blue}${bold}============${reset}"
	echo -e "${white}${bold}Boot enabled${reset}"
	echo -e "${blue}${bold}============${reset}"
	echo ""
	echo ""

#sudo -u splunk /opt/splunkforwarder/bin/splunk start
systemctl start SplunkForwarder.service


	echo -e "${blue}${bold}=======================${reset}"
	echo -e "${white}${bold}Starting Splunk Service${reset}"
	echo -e "${blue}${bold}=======================${reset}"
	echo ""
	echo ""

sleep 10

chown -R splunk:splunk /opt/splunkforwarder/

##################################
#Check the status of the Service.#
##################################

STATUS="$(systemctl is-active SplunkForwarder.service)"

if [ $STATUS == "active" ];

then

        echo -e "${blue}${bold}===========================================${reset}"
        echo -e "${white}${bold}Splunk forwarder is configured and running.${reset}"
        echo -e "${blue}${bold}===========================================${reset}"
	echo ""
	echo ""
	echo -e "${cyan}${bold}*******************************************${reset}"
        echo -e "${yellow}Splunk${reset}${green}${bold} > ${reset}${white}${bold}Finding your faults, just like mom${reset}"
        echo -e "${cyan}${bold}*******************************************${reset}"
	echo ""
	echo ""
	echo -e "${yellow}${bold}###############################################################${reset}"
	echo -e "${yellow}${bold}#${reset}   ${green}${bold}Successfully Installed the Universal Splunk forwarder!!!${reset}  ${yellow}${bold}#${reset}"
	echo -e "${yellow}${bold}#${reset}                  ${green}${bold} Go Splunking!!!${reset}                           ${yellow}${bold}#${reset}"
	echo -e "${yellow}${bold}###############################################################${reset}"




#####################################
#Cleanup any remaining Splunk files.#
#####################################

rm -rf ./linuxSplunkinstaller

else
        echo -e "${red}${bold}**********************************************************************************************************${reset}"
        echo  "Splunk forwarder configuration failed and is not running. Please check the install log located in /var/log"
        echo -e "${red}${bold}**********************************************************************************************************${reset}"


fi
